[build]
  command = "npm run build"
  publish = "site/public"

[build.environment]
  HUGO_VERSION = "0.123.7"

[context.deploy-preview]
  command = "hugo -s site --minify --buildDrafts --buildFuture"
